import { useAuth } from '@clerk/react';
import { useEffect, useState } from 'react';
import { optionalPlatform } from '../lib/platformApi';
import './platform-workspace.css';

const title = (v) => String(v || '').replaceAll('_', ' ').replace(/\b\w/g, (x) => x.toUpperCase());
const list = (value) => Array.isArray(value) ? value : [];
const Card = ({ eyebrow, title: heading, children }) => <section className="platform-card"><p>{eyebrow}</p><h2>{heading}</h2>{children}</section>;
const Empty = ({ children }) => <div className="platform-empty">{children}</div>;

export default function PlatformWorkspace() {
  const { getToken } = useAuth(); const [state, setState] = useState({}); const [amount, setAmount] = useState('25000');
  useEffect(() => { let live = true; Promise.all(['/playbooks','/rulings','/operations/health','/operations/metrics','/connectors','/partners','/governance/roles','/implementation/projects'].map((path) => optionalPlatform(path, getToken).then((value) => [path, value]))).then((items) => live && setState(Object.fromEntries(items))); return () => { live = false; }; }, [getToken]);
  const data = (path) => state[path]?.data || {}; const items = (path) => list(data(path).items || data(path).results || data(path));
  return <main className="platform-workspace" id="main-content"><header className="platform-hero"><p>PLATFORM CONTROL ROOM</p><h1>Trade decisions,<br /><em>made reviewable.</em></h1><span>Local rules, manual records, and approved adapters remain the baseline. Optional services only add reviewable context.</span></header>
    <div className="platform-grid">
      <Card eyebrow="CORRIDOR PLAYBOOKS" title="Published route guidance">{items('/playbooks').length ? <ul>{items('/playbooks').slice(0,4).map((x,i)=><li key={x.id||i}><strong>{x.name||x.corridor||'Corridor playbook'}</strong><span>{title(x.status||'published')} · {x.effective_date||'effective date not supplied'}</span></li>)}</ul> : <Empty>Local corridor guidance is used where configured. No live regulatory coverage is implied.</Empty>}</Card>
      <Card eyebrow="CLASSIFICATION" title="HS & rulings comparison"><div className="candidate"><strong>Manual candidate selection</strong><span>Search local curated references, compare citations, then record a human decision. This is advisory—not an official ruling.</span></div>{items('/rulings').length ? <ul>{items('/rulings').slice(0,3).map((x,i)=><li key={x.id||i}><strong>{x.code||x.title||'Reference candidate'}</strong><span>{x.source||'Local reference'} · review before use</span></li>)}</ul> : <Empty>No reference search is connected. Enter a classification decision only after broker/importer review.</Empty>}<button type="button">Record classification decision</button></Card>
      <Card eyebrow="LANDED COST" title="Deterministic scenario"><label>Declared goods value<input value={amount} onChange={(e)=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal" /></label><div className="scenario"><strong>{amount ? `Value input: ${amount}` : 'Value unknown'}</strong><span>Duty, tax, freight, insurance, and FX are intentionally unknown until sourced assumptions are saved.</span></div><small>Formulas use only saved assumptions. No tariff, tax, or FX amount is invented.</small></Card>
      <Card eyebrow="OPERATIONS" title="Health & safe metrics">{state['/operations/health']?.available ? <div className="metric-list">{Object.entries(data('/operations/health')).filter(([,v])=>typeof v !== 'object').slice(0,4).map(([k,v])=><span key={k}><b>{title(k)}</b>{String(v)}</span>)}</div> : <Empty>Operational health is not connected. This demo does not claim a production SLO.</Empty>}<small>Metrics exclude trade facts, party names, document text, and credentials.</small></Card>
      <Card eyebrow="CONNECTORS" title="Integration boundary">{items('/connectors').length ? <ul>{items('/connectors').slice(0,4).map((x,i)=><li key={x.id||i}><strong>{x.name||'Connector'}</strong><span>{title(x.status||'not configured')}</span></li>)}</ul> : <><div className="status-row"><b>CSV/manual import</b><span>Available baseline</span></div><div className="status-row"><b>Carrier / EDI</b><span>Requires approved vendor</span></div><div className="status-row"><b>Customs connection</b><span>Not connected</span></div></>}<button type="button">Prepare CSV mapping</button></Card>
      <Card eyebrow="SCREENING & CLEARANCE" title="Manual evidence cases"><div className="status-row"><b>Restricted-party screening</b><span>Not screened · manual review required</span></div><div className="status-row"><b>Customs clearance</b><span>Not filed · not connected</span></div><button type="button">Add manual evidence</button><small>No screening or filing outcome is inferred from this workspace.</small></Card>
      <Card eyebrow="ACCESS & GOVERNANCE" title="Scoped collaboration">{items('/partners').length || items('/governance/roles').length ? <ul>{[...items('/partners'),...items('/governance/roles')].slice(0,4).map((x,i)=><li key={x.id||i}><strong>{x.name||x.email||x.role||'Scoped access'}</strong><span>{title(x.status||x.role||'review required')}</span></li>)}</ul> : <Empty>Partner access and enterprise roles are not configured. SSO/SCIM requires enterprise approval.</Empty>}<button type="button">Review access checklist</button></Card>
      <Card eyebrow="IMPLEMENTATION TOOLKIT" title="Launch checklist">{items('/implementation/projects').length ? <ul>{items('/implementation/projects').slice(0,3).map((x,i)=><li key={x.id||i}><strong>{x.name||'Implementation project'}</strong><span>{title(x.status||'draft')}</span></li>)}</ul> : <ol className="checklist"><li>Confirm organization owner and roles</li><li>Validate local templates and corridor rules</li><li>Approve adapter prerequisites before activation</li><li>Export configuration for human review</li></ol>}<button type="button">Prepare configuration export</button></Card>
    </div><footer className="platform-disclaimer">Informational preparation workspace only. Review final classifications, filings, screening, and commercial decisions with appropriately authorized professionals.</footer>
  </main>;
}
